For Activity we use the dplyr package to relate various datasets and answer the questions

In [3]:
library(dplyr)

First we need to submit the given the dataset into a db which I named as my_db

In [4]:
my_db <- src_sqlite("C://Users//Fnu//Downloads//database.sqlite", create = T)

We apply the SQL Query and join the the two tables player and player_attributes of original data set

In [57]:
playerinfo <- tbl(my_db, sql("SELECT Player.player_api_id, PLayer.player_name,PLayer_Attributes.overall_rating,Player_Attributes.gk_diving,Player_Attributes.gk_handling,Player_Attributes.gk_kicking,Player_Attributes.gk_positioning,Player_Attributes.gk_reflexes FROM Player LEFT JOIN Player_Attributes ON Player.player_api_id=Player_Attributes.player_api_id"))

To get a particular variable which we will be the sum of the provided columns and Use mutate function

In [58]:
players <- mutate(playerinfo, gk_rating= gk_diving+gk_handling+gk_kicking+gk_positioning+gk_reflexes)

In [59]:
playering <- select(players,player_api_id,player_name,overall_rating,gk_rating) # To select the columns we need from the given dataset

Now we need to convert the table to Data Frame so that we can later on add it to the csv file

In [60]:
playering
playerss <- data.frame(playering)
playerss

Source:   query [?? x 4]
Database: sqlite 3.11.1 [C://Users//Fnu//Downloads//database.sqlite]

   player_api_id        player_name overall_rating gk_rating
           <int>              <chr>          <int>     <int>
1         505942 Aaron Appindangoye             61        38
2         505942 Aaron Appindangoye             61        38
3         505942 Aaron Appindangoye             62        43
4         505942 Aaron Appindangoye             67        43
5         505942 Aaron Appindangoye             67        43
6         155782    Aaron Cresswell             47       121
7         155782    Aaron Cresswell             51       117
8         155782    Aaron Cresswell             52       118
9         155782    Aaron Cresswell             53       121
10        155782    Aaron Cresswell             53       121
# ... with more rows

       player_api_id player_name         overall_rating gk_rating
1      505942        Aaron Appindangoye  61              38
2      505942        Aaron Appindangoye  61              38
3      505942        Aaron Appindangoye  62              43
4      505942        Aaron Appindangoye  67              43
5      505942        Aaron Appindangoye  67              43
6      155782        Aaron Cresswell     47             121
7      155782        Aaron Cresswell     51             117
8      155782        Aaron Cresswell     52             118
9      155782        Aaron Cresswell     53             121
10     155782        Aaron Cresswell     53             121
11     155782        Aaron Cresswell     54              46
12     155782        Aaron Cresswell     64              46
13     155782        Aaron Cresswell     65              46
14     155782        Aaron Cresswell     68              46
15     155782        Aaron Cresswell     69              46
16     155782        Aaron Cresswell     69              46
17     155782        Aaron Cresswell     69              46
18     155782        Aaron Cresswell     69              46
19     155782        Aaron Cresswell     69              46
20     155782        Aaron Cresswell     69              46
21     155782        Aaron Cresswell     69              46
22     155782        Aaron Cresswell     70              46
23     155782        Aaron Cresswell     70              46
24     155782        Aaron Cresswell     70              46
25     155782        Aaron Cresswell     70              46
26     155782        Aaron Cresswell     70              46
27     155782        Aaron Cresswell     70              46
28     155782        Aaron Cresswell     71              46
29     155782        Aaron Cresswell     71              46
30     155782        Aaron Cresswell     71              46
...    ...           ...                 ...            ...
183949 111182        Zsolt Laczko        67              35
183950 111182        Zsolt Laczko        68              35
183951 111182        Zsolt Laczko        68              35
183952 111182        Zsolt Laczko        68              35
183953 111182        Zsolt Laczko        68              35
183954  36491        Zsolt Low           67             119
183955  36491        Zsolt Low           67             119
183956  36491        Zsolt Low           67             128
183957  36491        Zsolt Low           68             128
183958  36491        Zsolt Low           68             128
183959  36491        Zsolt Low           68              45
183960  36491        Zsolt Low           68              45
183961  35506        Zurab Khizanishvili 67              58
183962  35506        Zurab Khizanishvili 67              58
183963  35506        Zurab Khizanishvili 67             140
183964  35506        Zurab Khizanishvili 70             140
183965  35506        Zurab Khizanishvili 70             140
183966  35506        Zurab Khizanishvili 72             140
183967  35506        Zurab Khizanishvili 75             140
183968  35506        Zurab Khizanishvili 78              89
183969  39902        Zvjezdan Misimovic  77             142
183970  39902        Zvjezdan Misimovic  78              50
183971  39902        Zvjezdan Misimovic  78             142
183972  39902        Zvjezdan Misimovic  78             142
183973  39902        Zvjezdan Misimovic  80             118
183974  39902        Zvjezdan Misimovic  81              50
183975  39902        Zvjezdan Misimovic  81              50
183976  39902        Zvjezdan Misimovic  81              50
183977  39902        Zvjezdan Misimovic  83              50
183978  39902        Zvjezdan Misimovic  83             153

Now we need the number_of_appear and number_of_leagues to answer certain question so we do the following code

In [9]:
leagueinfo <- tbl(my_db, sql("SELECT*from Match"))

In [65]:
homeLeague1 <- collect(group_by(leagueinfo, home_player_1)) 
homeLeague2 <- collect(group_by(leagueinfo, home_player_2)) 
homeLeague3 <- collect(group_by(leagueinfo, home_player_3)) 
homeLeague4 <- collect(group_by(leagueinfo, home_player_4))
homeLeague5 <- collect(group_by(leagueinfo, home_player_5)) 
homeLeague6 <- collect(group_by(leagueinfo, home_player_6)) 
homeLeague7 <- collect(group_by(leagueinfo, home_player_7)) 
homeLeague8 <- collect(group_by(leagueinfo, home_player_8)) 
homeLeague9 <- collect(group_by(leagueinfo, home_player_9))
homeLeague10 <- collect(group_by(leagueinfo, home_player_10))
homeLeague11 <- collect(group_by(leagueinfo, home_player_11))

      id    country_id league_id season    stage date
1      1    1          1         2008/2009  1    2008-08-17 00:00:00
2      2    1          1         2008/2009  1    2008-08-16 00:00:00
3      3    1          1         2008/2009  1    2008-08-16 00:00:00
4      4    1          1         2008/2009  1    2008-08-17 00:00:00
5      5    1          1         2008/2009  1    2008-08-16 00:00:00
6      6    1          1         2008/2009  1    2008-09-24 00:00:00
7      7    1          1         2008/2009  1    2008-08-16 00:00:00
8      8    1          1         2008/2009  1    2008-08-16 00:00:00
9      9    1          1         2008/2009  1    2008-08-16 00:00:00
10    10    1          1         2008/2009 10    2008-11-01 00:00:00
11    11    1          1         2008/2009 10    2008-10-31 00:00:00
12    12    1          1         2008/2009 10    2008-11-02 00:00:00
13    13    1          1         2008/2009 10    2008-11-01 00:00:00
14    14    1          1         2008/2009 10    2008-11-01 00:00:00
15    15    1          1         2008/2009 10    2008-11-01 00:00:00
16    16    1          1         2008/2009 10    2008-11-01 00:00:00
17    17    1          1         2008/2009 10    2008-11-01 00:00:00
18    18    1          1         2008/2009 10    2008-11-02 00:00:00
19    19    1          1         2008/2009 11    2008-11-08 00:00:00
20    20    1          1         2008/2009 11    2008-11-08 00:00:00
21    21    1          1         2008/2009 11    2008-11-09 00:00:00
22    22    1          1         2008/2009 11    2008-11-07 00:00:00
23    23    1          1         2008/2009 11    2008-11-08 00:00:00
24    24    1          1         2008/2009 11    2008-11-08 00:00:00
25    25    1          1         2008/2009 11    2008-11-08 00:00:00
26    26    1          1         2008/2009 11    2008-11-08 00:00:00
27    27    1          1         2008/2009 11    2008-11-09 00:00:00
28    28    1          1         2008/2009 12    2008-11-16 00:00:00
29    29    1          1         2008/2009 12    2008-11-15 00:00:00
30    30    1          1         2008/2009 12    2008-11-15 00:00:00
...   ...   ...        ...       ...       ...   ...
25950 25950 24558      24558     2015/2016 4     2015-08-08 00:00:00
25951 25951 24558      24558     2015/2016 4     2015-08-08 00:00:00
25952 25952 24558      24558     2015/2016 4     2015-08-09 00:00:00
25953 25953 24558      24558     2015/2016 4     2015-08-09 00:00:00
25954 25954 24558      24558     2015/2016 4     2015-08-09 00:00:00
25955 25955 24558      24558     2015/2016 5     2015-08-12 00:00:00
25956 25956 24558      24558     2015/2016 5     2015-08-12 00:00:00
25957 25957 24558      24558     2015/2016 5     2015-08-12 00:00:00
25958 25958 24558      24558     2015/2016 5     2015-08-13 00:00:00
25959 25959 24558      24558     2015/2016 5     2015-08-13 00:00:00
25960 25960 24558      24558     2015/2016 6     2015-08-22 00:00:00
25961 25961 24558      24558     2015/2016 6     2015-08-23 00:00:00
25962 25962 24558      24558     2015/2016 6     2015-08-23 00:00:00
25963 25963 24558      24558     2015/2016 6     2015-08-23 00:00:00
25964 25964 24558      24558     2015/2016 6     2015-08-22 00:00:00
25965 25965 24558      24558     2015/2016 7     2015-08-29 00:00:00
25966 25966 24558      24558     2015/2016 7     2015-08-29 00:00:00
25967 25967 24558      24558     2015/2016 7     2015-08-30 00:00:00
25968 25968 24558      24558     2015/2016 7     2015-08-30 00:00:00
25969 25969 24558      24558     2015/2016 7     2015-08-30 00:00:00
25970 25970 24558      24558     2015/2016 8     2015-09-12 00:00:00
25971 25971 24558      24558     2015/2016 8     2015-09-12 00:00:00
25972 25972 24558      24558     2015/2016 8     2015-09-13 00:00:00
25973 25973 24558      24558     2015/2016 8     2015-09-13 00:00:00
25974 25974 24558      24558     2015/2016 8     2015-09-13 00:00:00
25975 25975 24558      24558     2015/2016 9     2015-09-22 00:00:00
25976 25976 24558      24558     2015/2016 9     2015-09-23 00:00:00
25977 25977 24558      24558     2015/2016 9     2015-09-23 00:00:00
25978 25978 24558      24558     2015/2016 9     2015-09-22 00:00:00
25979 25979 24558      24558     2015/2016 9     2015-09-23 00:00:00
      match_api_id home_team_api_id away_team_api_id home_team_goal ... SJA
1     492473        9987             9993            1              ...  4
2     492474       10000             9994            0              ...  3
3     492475        9984             8635            0              ...  2
4     492476        9991             9998            5              ...  7
5     492477        7947             9985            1              ...  1
6     492478        8203             8342            1              ...  1
7     492479        9999             8571            2              ...  3
8     492480        4049             9996            1              ...  2
9     492481       10001             9986            1              ...  3
10    492564        8342             8571            4              ... 10
11    492565        9985             9986            1              ... 10
12    492566       10000             9991            0              ...  2
13    492567        9994             9998            0              ...  4
14    492568        7947            10001            2              ...  2
15    492569        8203             9999            1              ...  4
16    492570        9996             9984            0              ...  2
17    492571        4049             9987            1              ...  1
18    492572        9993             8635            1              ...  1
19    492573        8635             9994            2              ...  9
20    492574        9998             9996            0              ...  2
21    492575        9986             8342            2              ...  2
22    492576        9984            10000            2              ...  4
23    492577        9991             7947            1              ...  7
24    492578        9999             4049            1              ...  4
25    492579        8571             8203            0              ...  3
26    492580       10001             9987            1              ...  2
27    492581        9993             9985            1              ...  1
28    492582        8342             8635            1              ...  3
29    492583        9987             9999            1              ... 10
30    492584       10000             9993            2              ...  3
...   ...          ...              ...              ...                ...
25950 1992066       9956             7896            6              ... NA
25951 1992067      10199             9931            1              ... NA
25952 1992068      10190            10243            0              ... NA
25953 1992069       9824            10179            1              ... NA
25954 1992070      10192            10191            3              ... NA
25955 1992071       9931            10191            3              ... NA
25956 1992072      10192             7896            0              ... NA
25957 1992073      10199            10190            0              ... NA
25958 1992074      10179            10243            3              ... NA
25959 1992075       9824             9956            3              ... NA
25960 1992076       7896             9931            1              ... NA
25961 1992077      10179            10192            1              ... NA
25962 1992078      10190             9956            0              ... NA
25963 1992079      10191             9824            1              ... NA
25964 1992080      10243            10199            2              ... NA
25965 1992081       7896            10199            0              ... NA
25966 1992082       9824            10190            1              ... NA
25967 1992083      10191            10179            0              ... NA
25968 1992084       9931            10243            3              ... NA
25969 1992085       9956            10192            3              ... NA
25970 1992086       9931            10190            2              ... NA
25971 1992087      10192             9824            4              ... NA
25972 1992088      10199             9956            3              ... NA
25973 1992089      10243            10191            3              ... NA
25974 1992090      10179             7896            3              ... NA
25975 1992091      10190            10191            1              ... NA
25976 1992092       9824            10199            1              ... NA
25977 1992093       9956            10179            2              ... NA
25978 1992094       7896            10243            0              ... NA
25979 1992095      10192             9931            4              ... NA
      VCH  VCD  VCA  GBH  GBD  GBA BSH  BSD  BSA
1     1.65 3.40 4.50 1.78 3.25  4  1.73 3.40 4.20
2     2.00 3.25 3.25 1.85 3.25  3  1.91 3.25 3.60
3     2.35 3.25 2.65 2.50 3.20  2  2.30 3.20 2.75
4     1.45 3.75 6.50 1.50 3.75  5  1.44 3.75 6.50
5     4.50 3.40 1.65 4.50 3.50  1  4.75 3.30 1.67
6     4.35 3.40 1.70 4.50 3.40  1    NA   NA   NA
7     2.10 3.25 3.00 1.85 3.25  3  2.10 3.25 3.10
8     2.80 3.25 2.25 2.80 3.20  2  2.88 3.25 2.20
9     2.25 3.25 2.80 2.20 3.30  2  2.25 3.20 2.80
10    1.30 4.35 8.50 1.25 5.00 10  1.29 4.50 9.00
11    1.28 4.50 8.50 1.25 5.00 10  1.25 5.00 9.00
12    2.65 3.30 2.30 2.60 3.25  2  2.62 3.20 2.38
13    2.00 3.20 3.40 1.85 3.30  4  1.83 3.30 3.80
14    2.75 3.20 2.30 2.75 3.25  2  2.75 3.20 2.30
15    1.70 3.40 4.35 1.75 3.40  4  1.70 3.40 4.33
16    2.20 3.25 2.90 2.30 3.25  2  2.30 3.20 2.75
17    5.50 3.50 1.55 5.25 3.60  1  6.00 3.60 1.50
18    3.60 3.25 1.90 4.10 3.40  1  3.80 3.30 1.83
19    1.28 4.50 8.50 1.30 4.75  7  1.30 4.50 8.50
20    2.35 3.25 2.65 2.30 3.20  2  2.30 3.25 2.70
21    3.25 3.25 2.00 3.10 3.20  2  3.10 3.25 2.10
22    1.75 3.25 4.35 1.80 3.30  4  1.70 3.30 4.50
23    1.35 4.00 7.50 1.40 4.20  7  1.36 4.20 7.00
24    1.80 3.25 4.00 1.85 3.30  4  1.80 3.30 4.00
25    2.00 3.25 3.25 1.95 3.20  3  2.00 3.25 3.30
26    2.40 3.25 2.60 2.50 3.25  2  2.50 3.20 2.50
27    3.75 3.25 1.85 3.60 3.25  1  3.50 3.30 1.91
28    2.25 3.10 2.80 2.10 3.20  3  2.20 3.20 2.90
29    1.25 5.00 9.00 1.27 5.00  8  1.25 5.00 9.00
30    2.10 3.30 3.10 2.00 3.20  3  2.00 3.25 3.30
...   ...  ...  ...  ...  ...  ... ...  ...  ...
25950 NA   NA   NA   NA   NA   NA  NA   NA   NA
25951 NA   NA   NA   NA   NA   NA  NA   NA   NA
25952 NA   NA   NA   NA   NA   NA  NA   NA   NA
25953 NA   NA   NA   NA   NA   NA  NA   NA   NA
25954 NA   NA   NA   NA   NA   NA  NA   NA   NA
25955 NA   NA   NA   NA   NA   NA  NA   NA   NA
25956 NA   NA   NA   NA   NA   NA  NA   NA   NA
25957 NA   NA   NA   NA   NA   NA  NA   NA   NA
25958 NA   NA   NA   NA   NA   NA  NA   NA   NA
25959 NA   NA   NA   NA   NA   NA  NA   NA   NA
25960 NA   NA   NA   NA   NA   NA  NA   NA   NA
25961 NA   NA   NA   NA   NA   NA  NA   NA   NA
25962 NA   NA   NA   NA   NA   NA  NA   NA   NA
25963 NA   NA   NA   NA   NA   NA  NA   NA   NA
25964 NA   NA   NA   NA   NA   NA  NA   NA   NA
25965 NA   NA   NA   NA   NA   NA  NA   NA   NA
25966 NA   NA   NA   NA   NA   NA  NA   NA   NA
25967 NA   NA   NA   NA   NA   NA  NA   NA   NA
25968 NA   NA   NA   NA   NA   NA  NA   NA   NA
25969 NA   NA   NA   NA   NA   NA  NA   NA   NA
25970 NA   NA   NA   NA   NA   NA  NA   NA   NA
25971 NA   NA   NA   NA   NA   NA  NA   NA   NA
25972 NA   NA   NA   NA   NA   NA  NA   NA   NA
25973 NA   NA   NA   NA   NA   NA  NA   NA   NA
25974 NA   NA   NA   NA   NA   NA  NA   NA   NA
25975 NA   NA   NA   NA   NA   NA  NA   NA   NA
25976 NA   NA   NA   NA   NA   NA  NA   NA   NA
25977 NA   NA   NA   NA   NA   NA  NA   NA   NA
25978 NA   NA   NA   NA   NA   NA  NA   NA   NA
25979 NA   NA   NA   NA   NA   NA  NA   NA   NA

      id    country_id league_id season    stage date
1      1    1          1         2008/2009  1    2008-08-17 00:00:00
2      2    1          1         2008/2009  1    2008-08-16 00:00:00
3      3    1          1         2008/2009  1    2008-08-16 00:00:00
4      4    1          1         2008/2009  1    2008-08-17 00:00:00
5      5    1          1         2008/2009  1    2008-08-16 00:00:00
6      6    1          1         2008/2009  1    2008-09-24 00:00:00
7      7    1          1         2008/2009  1    2008-08-16 00:00:00
8      8    1          1         2008/2009  1    2008-08-16 00:00:00
9      9    1          1         2008/2009  1    2008-08-16 00:00:00
10    10    1          1         2008/2009 10    2008-11-01 00:00:00
11    11    1          1         2008/2009 10    2008-10-31 00:00:00
12    12    1          1         2008/2009 10    2008-11-02 00:00:00
13    13    1          1         2008/2009 10    2008-11-01 00:00:00
14    14    1          1         2008/2009 10    2008-11-01 00:00:00
15    15    1          1         2008/2009 10    2008-11-01 00:00:00
16    16    1          1         2008/2009 10    2008-11-01 00:00:00
17    17    1          1         2008/2009 10    2008-11-01 00:00:00
18    18    1          1         2008/2009 10    2008-11-02 00:00:00
19    19    1          1         2008/2009 11    2008-11-08 00:00:00
20    20    1          1         2008/2009 11    2008-11-08 00:00:00
21    21    1          1         2008/2009 11    2008-11-09 00:00:00
22    22    1          1         2008/2009 11    2008-11-07 00:00:00
23    23    1          1         2008/2009 11    2008-11-08 00:00:00
24    24    1          1         2008/2009 11    2008-11-08 00:00:00
25    25    1          1         2008/2009 11    2008-11-08 00:00:00
26    26    1          1         2008/2009 11    2008-11-08 00:00:00
27    27    1          1         2008/2009 11    2008-11-09 00:00:00
28    28    1          1         2008/2009 12    2008-11-16 00:00:00
29    29    1          1         2008/2009 12    2008-11-15 00:00:00
30    30    1          1         2008/2009 12    2008-11-15 00:00:00
...   ...   ...        ...       ...       ...   ...
25950 25950 24558      24558     2015/2016 4     2015-08-08 00:00:00
25951 25951 24558      24558     2015/2016 4     2015-08-08 00:00:00
25952 25952 24558      24558     2015/2016 4     2015-08-09 00:00:00
25953 25953 24558      24558     2015/2016 4     2015-08-09 00:00:00
25954 25954 24558      24558     2015/2016 4     2015-08-09 00:00:00
25955 25955 24558      24558     2015/2016 5     2015-08-12 00:00:00
25956 25956 24558      24558     2015/2016 5     2015-08-12 00:00:00
25957 25957 24558      24558     2015/2016 5     2015-08-12 00:00:00
25958 25958 24558      24558     2015/2016 5     2015-08-13 00:00:00
25959 25959 24558      24558     2015/2016 5     2015-08-13 00:00:00
25960 25960 24558      24558     2015/2016 6     2015-08-22 00:00:00
25961 25961 24558      24558     2015/2016 6     2015-08-23 00:00:00
25962 25962 24558      24558     2015/2016 6     2015-08-23 00:00:00
25963 25963 24558      24558     2015/2016 6     2015-08-23 00:00:00
25964 25964 24558      24558     2015/2016 6     2015-08-22 00:00:00
25965 25965 24558      24558     2015/2016 7     2015-08-29 00:00:00
25966 25966 24558      24558     2015/2016 7     2015-08-29 00:00:00
25967 25967 24558      24558     2015/2016 7     2015-08-30 00:00:00
25968 25968 24558      24558     2015/2016 7     2015-08-30 00:00:00
25969 25969 24558      24558     2015/2016 7     2015-08-30 00:00:00
25970 25970 24558      24558     2015/2016 8     2015-09-12 00:00:00
25971 25971 24558      24558     2015/2016 8     2015-09-12 00:00:00
25972 25972 24558      24558     2015/2016 8     2015-09-13 00:00:00
25973 25973 24558      24558     2015/2016 8     2015-09-13 00:00:00
25974 25974 24558      24558     2015/2016 8     2015-09-13 00:00:00
25975 25975 24558      24558     2015/2016 9     2015-09-22 00:00:00
25976 25976 24558      24558     2015/2016 9     2015-09-23 00:00:00
25977 25977 24558      24558     2015/2016 9     2015-09-23 00:00:00
25978 25978 24558      24558     2015/2016 9     2015-09-22 00:00:00
25979 25979 24558      24558     2015/2016 9     2015-09-23 00:00:00
      match_api_id home_team_api_id away_team_api_id home_team_goal ... SJA
1     492473        9987             9993            1              ...  4
2     492474       10000             9994            0              ...  3
3     492475        9984             8635            0              ...  2
4     492476        9991             9998            5              ...  7
5     492477        7947             9985            1              ...  1
6     492478        8203             8342            1              ...  1
7     492479        9999             8571            2              ...  3
8     492480        4049             9996            1              ...  2
9     492481       10001             9986            1              ...  3
10    492564        8342             8571            4              ... 10
11    492565        9985             9986            1              ... 10
12    492566       10000             9991            0              ...  2
13    492567        9994             9998            0              ...  4
14    492568        7947            10001            2              ...  2
15    492569        8203             9999            1              ...  4
16    492570        9996             9984            0              ...  2
17    492571        4049             9987            1              ...  1
18    492572        9993             8635            1              ...  1
19    492573        8635             9994            2              ...  9
20    492574        9998             9996            0              ...  2
21    492575        9986             8342            2              ...  2
22    492576        9984            10000            2              ...  4
23    492577        9991             7947            1              ...  7
24    492578        9999             4049            1              ...  4
25    492579        8571             8203            0              ...  3
26    492580       10001             9987            1              ...  2
27    492581        9993             9985            1              ...  1
28    492582        8342             8635            1              ...  3
29    492583        9987             9999            1              ... 10
30    492584       10000             9993            2              ...  3
...   ...          ...              ...              ...                ...
25950 1992066       9956             7896            6              ... NA
25951 1992067      10199             9931            1              ... NA
25952 1992068      10190            10243            0              ... NA
25953 1992069       9824            10179            1              ... NA
25954 1992070      10192            10191            3              ... NA
25955 1992071       9931            10191            3              ... NA
25956 1992072      10192             7896            0              ... NA
25957 1992073      10199            10190            0              ... NA
25958 1992074      10179            10243            3              ... NA
25959 1992075       9824             9956            3              ... NA
25960 1992076       7896             9931            1              ... NA
25961 1992077      10179            10192            1              ... NA
25962 1992078      10190             9956            0              ... NA
25963 1992079      10191             9824            1              ... NA
25964 1992080      10243            10199            2              ... NA
25965 1992081       7896            10199            0              ... NA
25966 1992082       9824            10190            1              ... NA
25967 1992083      10191            10179            0              ... NA
25968 1992084       9931            10243            3              ... NA
25969 1992085       9956            10192            3              ... NA
25970 1992086       9931            10190            2              ... NA
25971 1992087      10192             9824            4              ... NA
25972 1992088      10199             9956            3              ... NA
25973 1992089      10243            10191            3              ... NA
25974 1992090      10179             7896            3              ... NA
25975 1992091      10190            10191            1              ... NA
25976 1992092       9824            10199            1              ... NA
25977 1992093       9956            10179            2              ... NA
25978 1992094       7896            10243            0              ... NA
25979 1992095      10192             9931            4              ... NA
      VCH  VCD  VCA  GBH  GBD  GBA BSH  BSD  BSA
1     1.65 3.40 4.50 1.78 3.25  4  1.73 3.40 4.20
2     2.00 3.25 3.25 1.85 3.25  3  1.91 3.25 3.60
3     2.35 3.25 2.65 2.50 3.20  2  2.30 3.20 2.75
4     1.45 3.75 6.50 1.50 3.75  5  1.44 3.75 6.50
5     4.50 3.40 1.65 4.50 3.50  1  4.75 3.30 1.67
6     4.35 3.40 1.70 4.50 3.40  1    NA   NA   NA
7     2.10 3.25 3.00 1.85 3.25  3  2.10 3.25 3.10
8     2.80 3.25 2.25 2.80 3.20  2  2.88 3.25 2.20
9     2.25 3.25 2.80 2.20 3.30  2  2.25 3.20 2.80
10    1.30 4.35 8.50 1.25 5.00 10  1.29 4.50 9.00
11    1.28 4.50 8.50 1.25 5.00 10  1.25 5.00 9.00
12    2.65 3.30 2.30 2.60 3.25  2  2.62 3.20 2.38
13    2.00 3.20 3.40 1.85 3.30  4  1.83 3.30 3.80
14    2.75 3.20 2.30 2.75 3.25  2  2.75 3.20 2.30
15    1.70 3.40 4.35 1.75 3.40  4  1.70 3.40 4.33
16    2.20 3.25 2.90 2.30 3.25  2  2.30 3.20 2.75
17    5.50 3.50 1.55 5.25 3.60  1  6.00 3.60 1.50
18    3.60 3.25 1.90 4.10 3.40  1  3.80 3.30 1.83
19    1.28 4.50 8.50 1.30 4.75  7  1.30 4.50 8.50
20    2.35 3.25 2.65 2.30 3.20  2  2.30 3.25 2.70
21    3.25 3.25 2.00 3.10 3.20  2  3.10 3.25 2.10
22    1.75 3.25 4.35 1.80 3.30  4  1.70 3.30 4.50
23    1.35 4.00 7.50 1.40 4.20  7  1.36 4.20 7.00
24    1.80 3.25 4.00 1.85 3.30  4  1.80 3.30 4.00
25    2.00 3.25 3.25 1.95 3.20  3  2.00 3.25 3.30
26    2.40 3.25 2.60 2.50 3.25  2  2.50 3.20 2.50
27    3.75 3.25 1.85 3.60 3.25  1  3.50 3.30 1.91
28    2.25 3.10 2.80 2.10 3.20  3  2.20 3.20 2.90
29    1.25 5.00 9.00 1.27 5.00  8  1.25 5.00 9.00
30    2.10 3.30 3.10 2.00 3.20  3  2.00 3.25 3.30
...   ...  ...  ...  ...  ...  ... ...  ...  ...
25950 NA   NA   NA   NA   NA   NA  NA   NA   NA
25951 NA   NA   NA   NA   NA   NA  NA   NA   NA
25952 NA   NA   NA   NA   NA   NA  NA   NA   NA
25953 NA   NA   NA   NA   NA   NA  NA   NA   NA
25954 NA   NA   NA   NA   NA   NA  NA   NA   NA
25955 NA   NA   NA   NA   NA   NA  NA   NA   NA
25956 NA   NA   NA   NA   NA   NA  NA   NA   NA
25957 NA   NA   NA   NA   NA   NA  NA   NA   NA
25958 NA   NA   NA   NA   NA   NA  NA   NA   NA
25959 NA   NA   NA   NA   NA   NA  NA   NA   NA
25960 NA   NA   NA   NA   NA   NA  NA   NA   NA
25961 NA   NA   NA   NA   NA   NA  NA   NA   NA
25962 NA   NA   NA   NA   NA   NA  NA   NA   NA
25963 NA   NA   NA   NA   NA   NA  NA   NA   NA
25964 NA   NA   NA   NA   NA   NA  NA   NA   NA
25965 NA   NA   NA   NA   NA   NA  NA   NA   NA
25966 NA   NA   NA   NA   NA   NA  NA   NA   NA
25967 NA   NA   NA   NA   NA   NA  NA   NA   NA
25968 NA   NA   NA   NA   NA   NA  NA   NA   NA
25969 NA   NA   NA   NA   NA   NA  NA   NA   NA
25970 NA   NA   NA   NA   NA   NA  NA   NA   NA
25971 NA   NA   NA   NA   NA   NA  NA   NA   NA
25972 NA   NA   NA   NA   NA   NA  NA   NA   NA
25973 NA   NA   NA   NA   NA   NA  NA   NA   NA
25974 NA   NA   NA   NA   NA   NA  NA   NA   NA
25975 NA   NA   NA   NA   NA   NA  NA   NA   NA
25976 NA   NA   NA   NA   NA   NA  NA   NA   NA
25977 NA   NA   NA   NA   NA   NA  NA   NA   NA
25978 NA   NA   NA   NA   NA   NA  NA   NA   NA
25979 NA   NA   NA   NA   NA   NA  NA   NA   NA

In [11]:
awayLeague1 <- collect(group_by(leagueinfo, away_player_1)) 
awayLeague2 <- collect(group_by(leagueinfo, away_player_2)) 
awayLeague3 <- collect(group_by(leagueinfo, away_player_3)) 
awayLeague4 <- collect(group_by(leagueinfo, away_player_4))
awayLeague5 <- collect(group_by(leagueinfo, away_player_5)) 
awayLeague6 <- collect(group_by(leagueinfo, away_player_6)) 
awayLeague7 <- collect(group_by(leagueinfo, away_player_7)) 
awayLeague8 <- collect(group_by(leagueinfo, away_player_8)) 
awayLeague9 <- collect(group_by(leagueinfo, away_player_9))
awayLeague10 <- collect(group_by(leagueinfo, away_player_10))
awayLeague11 <- collect(group_by(leagueinfo, away_player_11))

In [12]:
home1 <- select(homeLeague1,player_api_id=home_player_1,league_id)
home2 <- select(homeLeague2,player_api_id=home_player_2,league_id)
home3 <- select(homeLeague3,player_api_id=home_player_3,league_id)
home4 <- select(homeLeague4,player_api_id=home_player_4,league_id)
home5 <- select(homeLeague5,player_api_id=home_player_5,league_id)
home6 <- select(homeLeague6,player_api_id=home_player_6,league_id)
home7 <- select(homeLeague7,player_api_id=home_player_7,league_id)
home8 <- select(homeLeague8,player_api_id=home_player_8,league_id)
home9 <- select(homeLeague9,player_api_id=home_player_9,league_id)
home10 <- select(homeLeague10,player_api_id=home_player_10,league_id)
home11 <- select(homeLeague11,player_api_id=home_player_11,league_id)

In [13]:
away1 <- select(awayLeague1,player_api_id=away_player_1,league_id)
away2 <- select(awayLeague2,player_api_id=away_player_2,league_id)
away3 <- select(awayLeague3,player_api_id=away_player_3,league_id)
away4 <- select(awayLeague4,player_api_id=away_player_4,league_id)
away5 <- select(awayLeague5,player_api_id=away_player_5,league_id)
away6 <- select(awayLeague6,player_api_id=away_player_6,league_id)
away7 <- select(awayLeague7,player_api_id=away_player_7,league_id)
away8 <- select(awayLeague8,player_api_id=away_player_8,league_id)
away9 <- select(awayLeague9,player_api_id=away_player_9,league_id)
away10 <- select(awayLeague10,player_api_id=away_player_10,league_id)
away11 <- select(awayLeague11,player_api_id=away_player_11,league_id)

We binded all these above calculated attributes so that we can use to get number_of_leagues

In [14]:
allbind <- rbind(home1,home2,home3,home4,home5,home6,home7,home8,home9,home10,home11,away1,away2,away3,away4,away5,away6,away7,away8,away9,away10,away11)

In [20]:
na.omit(allbind)

       player_api_id league_id
1       39890        1
2       38327        1
3       95597        1
4       30934        1
5       37990        1
6       38391        1
7       39153        1
8       37900        1
9       36835        1
10      38252        1
11      34480        1
12      33676        1
13      37937        1
14      38341        1
15      38318        1
16     104378        1
17      95597        1
18      38327        1
19      38391        1
20      30934        1
21      39153        1
22      37990        1
23      37900        1
24     148308        1
25      32990        1
26      33676        1
27      95597        1
28     104378        1
29      38252        1
30      38341        1
...    ...           ...
542252 178142        24558
542253 527103        24558
542254  67306        24558
542255 275122        24558
542256 232110        24558
542257 289732        24558
542258 178142        24558
542259  35831        24558
542260  67306        24558
542261 289472        24558
542262 527104        24558
542263  37554        24558
542264 289472        24558
542265 209371        24558
542266  34082        24558
542267  34082        24558
542268 119839        24558
542269 275122        24558
542270  67306        24558
542271 422412        24558
542272  72628        24558
542273 113227        24558
542274 289472        24558
542275 289732        24558
542276 178142        24558
542277 289732        24558
542278  95257        24558
542279 275122        24558
542280 194532        24558
542281 527103        24558

In [21]:
counting <- count(distinct(allbind,league_id,.keep_all= T))

Now we need to columns required from the database for data cleaning

In [40]:
 leagues <- na.omit(counting)
league_table <- select(leagues,player_api_id,num_of_leagues=n)
league_table

      player_api_id num_of_leagues
1     2625          1
2     2752          1
3     2768          1
4     2770          2
5     2790          1
6     2796          1
7     2802          2
8     2805          1
9     2857          1
10    2862          1
11    2907          1
12    2973          1
13    2977          1
14    2983          1
15    2984          1
16    3140          1
17    3204          1
18    3263          1
19    3264          1
20    3316          1
21    3329          1
22    3377          1
23    3441          1
24    3512          1
25    3517          1
26    3520          1
27    4747          1
28    4863          1
29    4902          1
30    4939          1
...   ...           ...
11031 701154        1
11032 703659        1
11033 704523        1
11034 705484        1
11035 706985        1
11036 710807        1
11037 715642        1
11038 716998        1
11039 717248        1
11040 717270        1
11041 717557        1
11042 719413        1
11043 720738        1
11044 721133        1
11045 722766        1
11046 723037        1
11047 725718        1
11048 726956        1
11049 728125        1
11050 728414        1
11051 728478        1
11052 730065        1
11053 733787        1
11054 742405        1
11055 743720        1
11056 744907        1
11057 746419        1
11058 748432        1
11059 750435        1
11060 750584        1

In [35]:
counting1 <- count(allbind,league_id)

In [36]:
appearences <- na.omit(counting1)

In [37]:
appearences

      player_api_id league_id n
1     2625          15722      90
2     2752          21518      81
3     2768          21518      71
4     2770              1      14
5     2770          21518       2
6     2790          21518      50
7     2796          21518       1
8     2802           1729      44
9     2802          21518     100
10    2805          21518     131
11    2857          21518       3
12    2862           7809      17
13    2907           4769       6
14    2973          13274      16
15    2977          21518       5
16    2983          21518      71
17    2984          21518      38
18    3140          17642      42
19    3204          17642      42
20    3263          17642      19
21    3264          17642       1
22    3316          21518       6
23    3329              1      85
24    3377          10257       1
25    3441          13274      74
26    3512           1729       4
27    3517          24558      17
28    3520           1729      70
29    4747          19694      36
30    4863              1      25
...   ...           ...       ...
13187 701154         4769      2
13188 703659        24558      1
13189 704523         4769      4
13190 705484        24558      4
13191 706985         1729      2
13192 710807        21518      1
13193 715642         4769      1
13194 716998         4769      1
13195 717248        17642      4
13196 717270         4769      1
13197 717557        13274      4
13198 719413         4769      3
13199 720738         4769      5
13200 721133        17642     15
13201 722766        21518     13
13202 723037        17642      7
13203 725718        13274      1
13204 726956        24558      4
13205 728125        19694      2
13206 728414        13274      1
13207 728478        15722      1
13208 730065        17642      1
13209 733787        24558      2
13210 742405         1729      1
13211 743720        24558      1
13212 744907        19694      1
13213 746419        17642      2
13214 748432         7809      2
13215 750435         1729      1
13216 750584        17642      1

In [38]:
final <- select(appearences,player_api_id,number_of_appear=n)

In [39]:
final

      player_api_id number_of_appear
1     2625           90
2     2752           81
3     2768           71
4     2770           14
5     2770            2
6     2790           50
7     2796            1
8     2802           44
9     2802          100
10    2805          131
11    2857            3
12    2862           17
13    2907            6
14    2973           16
15    2977            5
16    2983           71
17    2984           38
18    3140           42
19    3204           42
20    3263           19
21    3264            1
22    3316            6
23    3329           85
24    3377            1
25    3441           74
26    3512            4
27    3517           17
28    3520           70
29    4747           36
30    4863           25
...   ...           ...
13187 701154         2
13188 703659         1
13189 704523         4
13190 705484         4
13191 706985         2
13192 710807         1
13193 715642         1
13194 716998         1
13195 717248         4
13196 717270         1
13197 717557         4
13198 719413         3
13199 720738         5
13200 721133        15
13201 722766        13
13202 723037         7
13203 725718         1
13204 726956         4
13205 728125         2
13206 728414         1
13207 728478         1
13208 730065         1
13209 733787         2
13210 742405         1
13211 743720         1
13212 744907         1
13213 746419         2
13214 748432         2
13215 750435         1
13216 750584         1

WE have got the three tables and we need to merge them using common column of player_api_id

In [61]:
finale=merge(x=playerss,y=league_table, by="player_api_id",all.x=TRUE)

In [62]:
finale

       player_api_id player_name       overall_rating gk_rating num_of_leagues
1      2625          Patryk Rachwal,18 58              45       1
2      2625          Patryk Rachwal,18 58              45       1
3      2625          Patryk Rachwal,18 58              45       1
4      2625          Patryk Rachwal,18 58              45       1
5      2625          Patryk Rachwal,18 59              45       1
6      2625          Patryk Rachwal,18 60              45       1
7      2625          Patryk Rachwal,18 60             153       1
8      2625          Patryk Rachwal,18 61              45       1
9      2625          Patryk Rachwal,18 61              45       1
10     2625          Patryk Rachwal,18 61              45       1
11     2625          Patryk Rachwal,18 61              45       1
12     2625          Patryk Rachwal,18 61              45       1
13     2625          Patryk Rachwal,18 63             111       1
14     2625          Patryk Rachwal,18 63             153       1
15     2752          Diego Mainz       62              48       1
16     2752          Diego Mainz       62              48       1
17     2752          Diego Mainz       65              48       1
18     2752          Diego Mainz       65              48       1
19     2752          Diego Mainz       68              48       1
20     2752          Diego Mainz       69              48       1
21     2752          Diego Mainz       70              48       1
22     2752          Diego Mainz       70              48       1
23     2752          Diego Mainz       70              48       1
24     2752          Diego Mainz       70              48       1
25     2752          Diego Mainz       70              48       1
26     2752          Diego Mainz       70              48       1
27     2752          Diego Mainz       71              48       1
28     2752          Diego Mainz       71              48       1
29     2752          Diego Mainz       72              48       1
30     2752          Diego Mainz       72              48       1
...    ...           ...               ...            ...       ...
183949 743720        Charles Pickel    50             53        1
183950 743720        Charles Pickel    50             53        1
183951 743720        Charles Pickel    50             53        1
183952 743720        Charles Pickel    50             53        1
183953 744907        Greg Taylor       51             52        1
183954 744907        Greg Taylor       51             52        1
183955 744907        Greg Taylor       51             52        1
183956 744907        Greg Taylor       51             52        1
183957 744907        Greg Taylor       51             52        1
183958 744907        Greg Taylor       51             52        1
183959 744907        Greg Taylor       53             57        1
183960 744907        Greg Taylor       53             57        1
183961 744907        Greg Taylor       53             57        1
183962 744907        Greg Taylor       53             57        1
183963 744907        Greg Taylor       53             57        1
183964 746419        Francisco Afonso  59             42        1
183965 746419        Francisco Afonso  59             42        1
183966 748432        Fynn Arkenberg    58             46        1
183967 748432        Fynn Arkenberg    58             46        1
183968 750435        Rees Greenwood    56             48        1
183969 750435        Rees Greenwood    56             48        1
183970 750435        Rees Greenwood    56             48        1
183971 750435        Rees Greenwood    56             48        1
183972 750435        Rees Greenwood    56             48        1
183973 750435        Rees Greenwood    56             48        1
183974 750435        Rees Greenwood    56             48        1
183975 750435        Rees Greenwood    56             48        1
183976 750435        Rees Greenwood    60             48        1
183977 750584        Alexandre Azevedo 58             54        1
183978 750584        Alexandre Azevedo 58             54        1

In [63]:
playerfinale=merge(x=finale,y=final, by="player_api_id",all.x=TRUE)

In [64]:
playerfinale

       player_api_id player_name       overall_rating gk_rating num_of_leagues
1      2625          Patryk Rachwal,18 58              45       1
2      2625          Patryk Rachwal,18 58              45       1
3      2625          Patryk Rachwal,18 58              45       1
4      2625          Patryk Rachwal,18 58              45       1
5      2625          Patryk Rachwal,18 59              45       1
6      2625          Patryk Rachwal,18 60              45       1
7      2625          Patryk Rachwal,18 60             153       1
8      2625          Patryk Rachwal,18 61              45       1
9      2625          Patryk Rachwal,18 61              45       1
10     2625          Patryk Rachwal,18 61              45       1
11     2625          Patryk Rachwal,18 61              45       1
12     2625          Patryk Rachwal,18 61              45       1
13     2625          Patryk Rachwal,18 63             111       1
14     2625          Patryk Rachwal,18 63             153       1
15     2752          Diego Mainz       62              48       1
16     2752          Diego Mainz       62              48       1
17     2752          Diego Mainz       65              48       1
18     2752          Diego Mainz       65              48       1
19     2752          Diego Mainz       68              48       1
20     2752          Diego Mainz       69              48       1
21     2752          Diego Mainz       70              48       1
22     2752          Diego Mainz       70              48       1
23     2752          Diego Mainz       70              48       1
24     2752          Diego Mainz       70              48       1
25     2752          Diego Mainz       70              48       1
26     2752          Diego Mainz       70              48       1
27     2752          Diego Mainz       71              48       1
28     2752          Diego Mainz       71              48       1
29     2752          Diego Mainz       72              48       1
30     2752          Diego Mainz       72              48       1
...    ...           ...               ...            ...       ...
234209 743720        Charles Pickel    50             53        1
234210 743720        Charles Pickel    50             53        1
234211 743720        Charles Pickel    50             53        1
234212 743720        Charles Pickel    50             53        1
234213 744907        Greg Taylor       51             52        1
234214 744907        Greg Taylor       51             52        1
234215 744907        Greg Taylor       51             52        1
234216 744907        Greg Taylor       51             52        1
234217 744907        Greg Taylor       51             52        1
234218 744907        Greg Taylor       51             52        1
234219 744907        Greg Taylor       53             57        1
234220 744907        Greg Taylor       53             57        1
234221 744907        Greg Taylor       53             57        1
234222 744907        Greg Taylor       53             57        1
234223 744907        Greg Taylor       53             57        1
234224 746419        Francisco Afonso  59             42        1
234225 746419        Francisco Afonso  59             42        1
234226 748432        Fynn Arkenberg    58             46        1
234227 748432        Fynn Arkenberg    58             46        1
234228 750435        Rees Greenwood    56             48        1
234229 750435        Rees Greenwood    56             48        1
234230 750435        Rees Greenwood    56             48        1
234231 750435        Rees Greenwood    56             48        1
234232 750435        Rees Greenwood    56             48        1
234233 750435        Rees Greenwood    56             48        1
234234 750435        Rees Greenwood    56             48        1
234235 750435        Rees Greenwood    56             48        1
234236 750435        Rees Greenwood    60             48        1
234237 750584        Alexandre Azevedo 58             54        1
234238 750584        Alexandre Azevedo 58             54        1
       number_of_appear
1      90
2      90
3      90
4      90
5      90
6      90
7      90
8      90
9      90
10     90
11     90
12     90
13     90
14     90
15     81
16     81
17     81
18     81
19     81
20     81
21     81
22     81
23     81
24     81
25     81
26     81
27     81
28     81
29     81
30     81
...    ...
234209 1
234210 1
234211 1
234212 1
234213 1
234214 1
234215 1
234216 1
234217 1
234218 1
234219 1
234220 1
234221 1
234222 1
234223 1
234224 2
234225 2
234226 2
234227 2
234228 1
234229 1
234230 1
234231 1
234232 1
234233 1
234234 1
234235 1
234236 1
234237 1
234238 1

Now we need to Group by the data to remove the redudancy and get the maximum value of attributes of any particular player

In [133]:
csvfilefinal <- sqldf("SELECT * FROM playerfinale GROUP BY player_name" )

In [134]:
csvfilefinal

      player_api_id player_name                 overall_rating gk_rating
1     505942        Aaron Appindangoye          67              43
2     155782        Aaron Cresswell             74              51
3     162549        Aaron Doran                 71              56
4      30572        Aaron Galindo               75             111
5      23780        Aaron Hughes                78             129
6      27316        Aaron Hunt                  79              60
7     564793        Aaron Kuhl                  61              64
8      30895        Aaron Lennon                84             146
9     528212        Aaron Lennox                48             237
10    101042        Aaron Meijers               69              54
11     23889        Aaron Mokoena               75             154
12    231592        Aaron Mooy                  75              54
13    163222        Aaron Muirhead              63              38
14     40719        Aaron Niguez                71              61
15     75489        Aaron Ramsey                83              40
16    597948        Aaron Splaine               55              55
17    161644        Aaron Taylor-Sinclair       65              49
18     23499        Aaron Wilbraham             67              54
19    120919        Aatif Chahechouhe           77              50
20     46447        Abasse Ba                   68             111
21    167027        Abdelaziz Barrada           76              42
22    245653        Abdelfettah Boukhriss       64              51
23    128456        Abdelhamid El Kaoutari      73              47
24     42664        Abdelkader Ghezzal          73              40
25    425950        Abdellah Zoubir             59              62
26     38423        Abdelmajid Oulmers          70             129
27      3264        Abdelmalek Cherrad          62              49
28    467485        Abdelmalek El Hasnaoui      63              52
29    306735        Abdelouahed Chakhsi         56              46
30     41659        Abderrazak Jadid            71              59
...   ...           ...                         ...            ...
10819 290868        Zhi-Gin Lam                 68              58
10820 169594        Zie Diabate                 65              59
10821 244953        Ziggy Gordon                64              51
10822 200607        Ziguy Badibanga             64              50
10823 642618        Zinedine Machach            67              52
10824 277772        Zinho Gano                  67              53
10825 246332        Ziri Hammar                 65              60
10826 532766        Zizo                        63              43
10827  27305        Zlatan Bajramovic           78             127
10828  35724        Zlatan Ibrahimovic          90              59
10829  12574        Zlatan Ljubijankic          72              52
10830  39494        Zlatko Dedic                71              60
10831  17233        Zlatko Janjic               66              59
10832  42860        Zlatko Junuzovic            79              58
10833  37128        Zola Matumona               68              50
10834  24737        Zoltan Gera                 77             147
10835 107281        Zoltan Stieber              73              44
10836  39801        Zoltan Szelesi              70             135
10837 491794        Zoran Josipovic             60              46
10838  56929        Zoran Rendulic              66              57
10839  99031        Zoran Tosic                 80              56
10840 192132        Zouhaier Dhaouadhi          64              54
10841 282473        Zouhair Feddal              75              57
10842  26357        Zoumana Camara              77             119
10843 111182        Zsolt Laczko                68              35
10844  36491        Zsolt Low                   68              45
10845  35506        Zurab Khizanishvili         78              89
10846  39902        Zvjezdan Misimovic          83             153
10847  11833        de Oliveira Cleber Monteiro 69              71
10848  38804        dos Santos Fabio Junior     70              55
      num_of_leagues number_of_appear
1     1                8
2     1               75
3     1              104
4     1               10
5     1              162
6     1              158
7     1                5
8     1              181
9     1                1
10    1              167
11    1               30
12    1               10
13    1               21
14    2               23
15    1              133
16    1                2
17    1               36
18    1                3
19    1                1
20    1               16
21    2               55
22    1                1
23    2                7
24    2                9
25    1                3
26    1               32
27    1                1
28    1                5
29    1               74
30    2                5
...   ...            ...
10819 1               15
10820 2               12
10821 1               64
10822 2                3
10823 1               10
10824 1               30
10825 1                4
10826 1               28
10827 1                7
10828 3               23
10829 1               65
10830 1               15
10831 1                1
10832 1              127
10833 1               43
10834 1               71
10835 1               35
10836 1               11
10837 1                1
10838 1                6
10839 1                9
10840 1                1
10841 2               28
10842 1              102
10843 1                7
10844 1               15
10845 1                3
10846 1               64
10847 1               64
10848 1               28

Finally we write the dataframe having all atributes required in player.csv file

In [135]:
write.csv(csvfilefinal,file="player.csv")

After dealing with palyer attributes we need to use the team columns and tables

In [185]:
teaminfo <- tbl(my_db, sql("SELECT * FROM Team LEFT JOIN Team_Attributes ON Team.team_api_id=Team_Attributes.team_api_id"))

We join the team and team_attributes tables of the dataset and the sum the attributes and usae the mutate function

In [92]:
teams <- mutate(teaminfo, build_up_play = buildUpPlaySpeed+buildUpPlayDribbling+buildUpPlayPassing)
teamss <- mutate(teams, chance_creation=chanceCreationPassing+chanceCreationCrossing+chanceCreationShooting)
teamsss <- mutate(teamss, defense_work=defencePressure+defenceAggression+defenceTeamWidth)

In [93]:
#chance_creation=chanceCreationPassing+chanceCreationCrossing+chanceCreationShooting, defense = defencePressure+defenseAggression+defenseTeamWidth)\
teamsss

Source:   query [?? x 33]
Database: sqlite 3.11.1 [C://Users//Fnu//Downloads//database.sqlite]

      id team_api_id team_fifa_api_id team_long_name team_short_name `id:1`
   <int>       <int>            <int>          <chr>           <chr>  <int>
1      1        9987              673       KRC Genk             GEN    485
2      1        9987              673       KRC Genk             GEN    486
3      1        9987              673       KRC Genk             GEN    487
4      1        9987              673       KRC Genk             GEN    488
5      1        9987              673       KRC Genk             GEN    489
6      1        9987              673       KRC Genk             GEN    490
7      2        9993              675   Beerschot AC             BAC    149
8      2        9993              675   Beerschot AC             BAC    150
9      2        9993              675   Beerschot AC             BAC    151
10     2        9993              675   Beerschot AC             BAC    152
# ... with more rows, and 27 more variables: `team_fifa_api_id:1` <int>,
#   `team_api_id:1` <int>, date <chr>, buildUpPlaySpeed <int>,
#   buildUpPlaySpeedClass <chr>, buildUpPlayDribbling <int>,
#   buildUpPlayDribblingClass <chr>, buildUpPlayPassing <int>,
#   buildUpPlayPassingClass <chr>, buildUpPlayPositioningClass <chr>,
#   chanceCreationPassing <int>, chanceCreationPassingClass <chr>,
#   chanceCreationCrossing <int>, chanceCreationCrossingClass <chr>,
#   chanceCreationShooting <int>, chanceCreationShootingClass <chr>,
#   chanceCreationPositioningClass <chr>, defencePressure <int>,
#   defencePressureClass <chr>, defenceAggression <int>,
#   defenceAggressionClass <chr>, defenceTeamWidth <int>,
#   defenceTeamWidthClass <chr>, defenceDefenderLineClass <chr>,
#   build_up_play <int>, chance_creation <int>, defense_work <int>

To clean the dataset we only select the columns we need

In [214]:
finalteams <- select(teamsss,team_api_id,team_long_name,build_up_play,chance_creation,defense_work)

In [215]:
finalteam <- data.frame(finalteams)

In [216]:
adata <- tbl(my_db,sql("SELECT home_team_api_id,away_team_api_id,home_team_goal,away_team_goal FROM MATCH"))

In [217]:
adataF <- data.frame(adata)
adataF

      home_team_api_id away_team_api_id home_team_goal away_team_goal
1      9987             9993            1              1
2     10000             9994            0              0
3      9984             8635            0              3
4      9991             9998            5              0
5      7947             9985            1              3
6      8203             8342            1              1
7      9999             8571            2              2
8      4049             9996            1              2
9     10001             9986            1              0
10     8342             8571            4              1
11     9985             9986            1              2
12    10000             9991            0              2
13     9994             9998            0              0
14     7947            10001            2              2
15     8203             9999            1              2
16     9996             9984            0              1
17     4049             9987            1              3
18     9993             8635            1              3
19     8635             9994            2              3
20     9998             9996            0              0
21     9986             8342            2              2
22     9984            10000            2              0
23     9991             7947            1              1
24     9999             4049            1              2
25     8571             8203            0              0
26    10001             9987            1              0
27     9993             9985            1              3
28     8342             8635            1              1
29     9987             9999            1              1
30    10000             9993            2              2
...   ...              ...              ...            ...
25950  9956             7896            6              1
25951 10199             9931            1              3
25952 10190            10243            0              2
25953  9824            10179            1              1
25954 10192            10191            3              1
25955  9931            10191            3              1
25956 10192             7896            0              1
25957 10199            10190            0              1
25958 10179            10243            3              1
25959  9824             9956            3              3
25960  7896             9931            1              3
25961 10179            10192            1              3
25962 10190             9956            0              2
25963 10191             9824            1              0
25964 10243            10199            2              5
25965  7896            10199            0              1
25966  9824            10190            1              0
25967 10191            10179            0              2
25968  9931            10243            3              1
25969  9956            10192            3              2
25970  9931            10190            2              1
25971 10192             9824            4              0
25972 10199             9956            3              3
25973 10243            10191            3              3
25974 10179             7896            3              0
25975 10190            10191            1              0
25976  9824            10199            1              2
25977  9956            10179            2              0
25978  7896            10243            0              0
25979 10192             9931            4              3

We have almost got all the attributes except the goals so we do the following computations to get that particular attribute

In [218]:
library(sqldf)
adatahome <- sqldf("SELECT home_team_api_id, sum(home_team_goal) as home_goal  FROM adataF GROUP BY home_team_api_id")
adataaway <- sqldf("SELECT away_team_api_id,sum(away_team_goal) as team_goal FROM adataF GROUP BY away_team_api_id")
awayhome <- sqldf("SELECT home_team_api_id as team_api_id, (home_goal+team_goal) as sum_goal FROM adatahome LEFT JOIN adataaway WHERE adatahome.home_team_api_id=adataaway.away_team_api_id")

In [229]:
library(sqldf)
#teamfinale <- na.omit(finalteam)
#teamfinale
teamfinal <- sqldf("SELECT * FROM finalteam GROUP BY team_api_id" )
teamfinal

     team_api_id team_long_name          build_up_play chance_creation
5     9987       KRC Genk                148           171
6     9987       KRC Genk                148           155
15   10000       SV Zulte-Waregem        147           131
16   10000       SV Zulte-Waregem        147           131
21    9994       Sporting Lokeren        159           154
22    9994       Sporting Lokeren        159           154
27    9984       KSV Cercle Brugge       145           152
28    9984       KSV Cercle Brugge       145           152
33    8635       RSC Anderlecht          149           160
34    8635       RSC Anderlecht          149           160
39    9991       KAA Gent                142           128
40    9991       KAA Gent                142           142
43    9998       RAEC Mons               160           168
49    9985       Standard de Liège       161           173
50    9985       Standard de Liège       161           173
55    8203       KV Mechelen             134           150
56    8203       KV Mechelen             134           150
61    8342       Club Brugge KV          139           146
62    8342       Club Brugge KV          139           146
68    8571       KV Kortrijk             129           134
69    8571       KV Kortrijk             129           134
71    9996       Royal Excel Mouscron    150           150
72    9996       Royal Excel Mouscron    150           150
76   10001       KVC Westerlo            148           144
80    9986       Sporting Charleroi      160           146
81    9986       Sporting Charleroi      160           146
88    9989       Lierse SK               171           169
89    9989       Lierse SK               171           169
93    1773       Oud-Heverlee Leuven     153           157
95    8475       Waasland-Beveren        122            98
...  ...         ...                     ...           ...
1385  9910       RC Celta de Vigo        169           179
1386  9910       RC Celta de Vigo        152           139
1391 10268       Elche CF                171           164
1392 10268       Elche CF                151           164
1393  8372       SD Eibar                165           179
1394  8372       SD Eibar                165           166
1399  7869       Córdoba CF              146           154
1400  7869       Córdoba CF              141           171
1405  8306       UD Las Palmas           147           148
1406  8306       UD Las Palmas           147           148
1411  9956       Grasshopper Club Zürich 164           152
1412  9956       Grasshopper Club Zürich 164           152
1419 10192       BSC Young Boys          172           151
1420 10192       BSC Young Boys          172           151
1425  9931       FC Basel                170           186
1426  9931       FC Basel                170           186
1428  9930       FC Aarau                156           181
1429  9930       FC Aarau                142           181
1434 10179       FC Sion                 155           165
1435 10179       FC Sion                 155           165
1440 10199       FC Luzern               165           160
1441 10199       FC Luzern               165           160
1442  9824       FC Vaduz                141           137
1450 10243       FC Zürich               157           151
1451 10243       FC Zürich               157           151
1455 10190       FC St. Gallen           146           115
1456 10190       FC St. Gallen           146           115
1460 10191       FC Thun                 152           166
1461 10191       FC Thun                 152           166
1468  7730       FC Lausanne-Sports      141           164
     defense_work
5    147
6    163
15   139
16   139
21   149
22   149
27   168
28   168
33   175
34   164
39   166
40   155
43   138
49   151
50   151
55   145
56   145
61   158
62   158
68   143
69   143
71   140
72   140
76   146
80   139
81   136
88   152
89   152
93   137
95    97
...  ...
1385 159
1386 169
1391 158
1392 158
1393 142
1394 142
1399 129
1400 129
1405 149
1406 149
1411 126
1412 126
1419 128
1420 128
1425 158
1426 158
1428 145
1429 145
1434 146
1435 146
1440 151
1441 151
1442 133
1450 146
1451 146
1455 133
1456 128
1460 145
1461 145
1468 145

    team_api_id team_long_name               build_up_play chance_creation
1   1601        Ruch Chorzów                 133           176
2   1773        Oud-Heverlee Leuven          153           157
3   1957        Jagiellonia Bialystok        158           152
4   2033        S.C. Olhanense               147           134
5   2182        Lech Poznan                  147           196
6   2183        P. Warszawa                   NA           131
7   2186        Cracovia                     125           165
8   4049        Tubize                        NA            NA
9   4064        Feirense                      NA            NA
10  4087        Évian Thonon Gaillard FC     149           164
11  4170        US Boulogne Cote D'Opale      NA           154
12  6269        Novara                       179           168
13  6351        KAS Eupen                     NA           160
14  6367        Uniao da Madeira              NA            NA
15  6391        GFC Ajaccio                  153           163
16  6403        FC Paços de Ferreira         142           169
17  6413        PEC Zwolle                   136           165
18  6421        Leixões SC                    NA           165
19  6433        Go Ahead Eagles              160           131
20  6493        AC Bellinzona                 NA           148
21  6547        FC Penafiel                  147           146
22  6601        FC Volendam                   NA            NA
23  6631        FC Dordrecht                 134           176
24  7730        FC Lausanne-Sports           141           164
25  7788        SC Cambuur                   136           134
26  7794        SC Bastia                    174           156
27  7819        SM Caen                      157           155
28  7841        Rio Ave FC                   157           177
29  7842        Estoril Praia                167           139
30  7844        Vitória Guimarães            131           173
... ...         ...                          ...           ...
270  10214      CD Nacional                  167           150
271  10215      Académica de Coimbra         150           166
272  10217      ADO Den Haag                 162           145
273  10218      Excelsior                    163           136
274  10219      RKC Waalwijk                 142           133
275  10228      SC Heerenveen                150           152
276  10229      AZ                           154           173
277  10233      Genoa                        184           134
278  10235      Feyenoord                    131           146
279  10238      Vitória Setúbal              149           158
280  10242      ES Troyes AC                 148           147
281  10243      FC Zürich                    157           151
282  10249      Montpellier Hérault SC       162           142
283  10251      Hibernian                    148           139
284  10252      Aston Villa                  154           146
285  10260      Manchester United            124           133
286  10261      Newcastle United             152           147
287  10264      SC Braga                     145           166
288  10265      Wisla Kraków                 119           101
289  10267      Valencia CF                  116           146
290  10268      Elche CF                     151           164
291  10269      VfB Stuttgart                155           172
292  10278      Hércules Club de Fútbol      154           178
293  10281      Real Valladolid              148           147
294 108893      AC Arles-Avignon             156           138
295 158085      FC Arouca                    170           160
296 177361      Termalica Bruk-Bet Nieciecza  NA            NA
297 188163      Tondela                       NA            NA
298 208931      Carpi                        190           160
299 274581      Royal Excel Mouscron         150           150
    defense_work
1   136
2   137
3   162
4   105
5   153
6   139
7   157
8    NA
9    NA
10  140
11  155
12  138
13  155
14   NA
15  141
16  139
17  181
18   90
19  141
20  138
21  121
22   NA
23  164
24  145
25  138
26  147
27  136
28  153
29  150
30  141
... ...
270 141
271 138
272 142
273 106
274  99
275 138
276 166
277 127
278 129
279 132
280 137
281 146
282 157
283 124
284 133
285 163
286 131
287 120
288 157
289 147
290 158
291 117
292 160
293 134
294 158
295 113
296  NA
297  NA
298 115
299 140

So finally combine the tables using merge command by commom attribute team_api_id

In [231]:
teamfilefinale=merge(x=awayhome,y=teamfinal, by="team_api_id",all.x=TRUE)
teamfilefinale
write.csv(teamfilefinale,file="team.csv")

    team_api_id sum_goal team_long_name               build_up_play
1   1601        280      Ruch Chorzów                 133
2   1773        126      Oud-Heverlee Leuven          153
3   1957        287      Jagiellonia Bialystok        158
4   2033        138      S.C. Olhanense               147
5   2182        372      Lech Poznan                  147
6   2183        184      P. Warszawa                   NA
7   2186        235      Cracovia                     125
8   4049         35      Tubize                        NA
9   4064         27      Feirense                      NA
10  4087        180      Évian Thonon Gaillard FC     149
11  4170         31      US Boulogne Cote D'Opale      NA
12  6269         34      Novara                       179
13  6351         28      KAS Eupen                     NA
14  6367         27      Uniao da Madeira              NA
15  6391         37      GFC Ajaccio                  153
16  6403        292      FC Paços de Ferreira         142
17  6413        204      PEC Zwolle                   136
18  6421         55      Leixões SC                    NA
19  6433         74      Go Ahead Eagles              160
20  6493        128      AC Bellinzona                 NA
21  6547         29      FC Penafiel                  147
22  6601         38      FC Volendam                   NA
23  6631         24      FC Dordrecht                 134
24  7730         99      FC Lausanne-Sports           141
25  7788        119      SC Cambuur                   136
26  7794        165      SC Bastia                    174
27  7819        220      SM Caen                      157
28  7841        248      Rio Ave FC                   157
29  7842        167      Estoril Praia                167
30  7844        300      Vitória Guimarães            131
... ...         ...      ...                          ...
270  10214      332      CD Nacional                  167
271  10215      240      Académica de Coimbra         150
272  10217      366      ADO Den Haag                 162
273  10218      154      Excelsior                    163
274  10219      153      RKC Waalwijk                 142
275  10228      470      SC Heerenveen                150
276  10229      492      AZ                           154
277  10233      392      Genoa                        184
278  10235      489      Feyenoord                    131
279  10238      238      Vitória Setúbal              149
280  10242       71      ES Troyes AC                 148
281  10243      468      FC Zürich                    157
282  10249      344      Montpellier Hérault SC       162
283  10251      259      Hibernian                    148
284  10252      335      Aston Villa                  154
285  10260      582      Manchester United            124
286  10261      324      Newcastle United             152
287  10264      398      SC Braga                     145
288  10265      332      Wisla Kraków                 119
289  10267      484      Valencia CF                  116
290  10268       65      Elche CF                     151
291  10269      415      VfB Stuttgart                155
292  10278       36      Hércules Club de Fútbol      154
293  10281      170      Real Valladolid              148
294 108893       21      AC Arles-Avignon             156
295 158085      101      FC Arouca                    170
296 177361       33      Termalica Bruk-Bet Nieciecza  NA
297 188163       34      Tondela                       NA
298 208931       37      Carpi                        190
299 274581       71      Royal Excel Mouscron         150
    chance_creation defense_work
1   176             136
2   157             137
3   152             162
4   134             105
5   196             153
6   131             139
7   165             157
8    NA              NA
9    NA              NA
10  164             140
11  154             155
12  168             138
13  160             155
14   NA              NA
15  163             141
16  169             139
17  165             181
18  165              90
19  131             141
20  148             138
21  146             121
22   NA              NA
23  176             164
24  164             145
25  134             138
26  156             147
27  155             136
28  177             153
29  139             150
30  173             141
... ...             ...
270 150             141
271 166             138
272 145             142
273 136             106
274 133              99
275 152             138
276 173             166
277 134             127
278 146             129
279 158             132
280 147             137
281 151             146
282 142             157
283 139             124
284 146             133
285 133             163
286 147             131
287 166             120
288 101             157
289 146             147
290 164             158
291 172             117
292 178             160
293 147             134
294 138             158
295 160             113
296  NA              NA
297  NA              NA
298 160             115
299 150             140