In this all questions are being specified 
The library used is dplyr
The files player.csv and team.csv are used to answer all the computations

In [3]:
library(dplyr)

Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

In [1]:
Frame <- read.csv(file="player.csv",header=TRUE,sep=",")
Frame

      X     player_api_id player_name                 overall_rating gk_rating
1      1    505942        Aaron Appindangoye          67              43
2      2    155782        Aaron Cresswell             74              51
3      3    162549        Aaron Doran                 71              56
4      4     30572        Aaron Galindo               75             111
5      5     23780        Aaron Hughes                78             129
6      6     27316        Aaron Hunt                  79              60
7      7    564793        Aaron Kuhl                  61              64
8      8     30895        Aaron Lennon                84             146
9      9    528212        Aaron Lennox                48             237
10    10    101042        Aaron Meijers               69              54
11    11     23889        Aaron Mokoena               75             154
12    12    231592        Aaron Mooy                  75              54
13    13    163222        Aaron Muirhead              63              38
14    14     40719        Aaron Niguez                71              61
15    15     75489        Aaron Ramsey                83              40
16    16    597948        Aaron Splaine               55              55
17    17    161644        Aaron Taylor-Sinclair       65              49
18    18     23499        Aaron Wilbraham             67              54
19    19    120919        Aatif Chahechouhe           77              50
20    20     46447        Abasse Ba                   68             111
21    21    167027        Abdelaziz Barrada           76              42
22    22    245653        Abdelfettah Boukhriss       64              51
23    23    128456        Abdelhamid El Kaoutari      73              47
24    24     42664        Abdelkader Ghezzal          73              40
25    25    425950        Abdellah Zoubir             59              62
26    26     38423        Abdelmajid Oulmers          70             129
27    27      3264        Abdelmalek Cherrad          62              49
28    28    467485        Abdelmalek El Hasnaoui      63              52
29    29    306735        Abdelouahed Chakhsi         56              46
30    30     41659        Abderrazak Jadid            71              59
...   ...   ...           ...                         ...            ...
10819 10819 290868        Zhi-Gin Lam                 68              58
10820 10820 169594        Zie Diabate                 65              59
10821 10821 244953        Ziggy Gordon                64              51
10822 10822 200607        Ziguy Badibanga             64              50
10823 10823 642618        Zinedine Machach            67              52
10824 10824 277772        Zinho Gano                  67              53
10825 10825 246332        Ziri Hammar                 65              60
10826 10826 532766        Zizo                        63              43
10827 10827  27305        Zlatan Bajramovic           78             127
10828 10828  35724        Zlatan Ibrahimovic          90              59
10829 10829  12574        Zlatan Ljubijankic          72              52
10830 10830  39494        Zlatko Dedic                71              60
10831 10831  17233        Zlatko Janjic               66              59
10832 10832  42860        Zlatko Junuzovic            79              58
10833 10833  37128        Zola Matumona               68              50
10834 10834  24737        Zoltan Gera                 77             147
10835 10835 107281        Zoltan Stieber              73              44
10836 10836  39801        Zoltan Szelesi              70             135
10837 10837 491794        Zoran Josipovic             60              46
10838 10838  56929        Zoran Rendulic              66              57
10839 10839  99031        Zoran Tosic                 80              56
10840 10840 192132        Zouhaier Dhaouadhi          64              54
10841 10841 282473        Zouhair Feddal              75              57
10842 10842  26357        Zoumana Camara              77             119
10843 10843 111182        Zsolt Laczko                68              35
10844 10844  36491        Zsolt Low                   68              45
10845 10845  35506        Zurab Khizanishvili         78              89
10846 10846  39902        Zvjezdan Misimovic          83             153
10847 10847  11833        de Oliveira Cleber Monteiro 69              71
10848 10848  38804        dos Santos Fabio Junior     70              55
      num_of_leagues number_of_appear
1     1                8
2     1               75
3     1              104
4     1               10
5     1              162
6     1              158
7     1                5
8     1              181
9     1                1
10    1              167
11    1               30
12    1               10
13    1               21
14    2               23
15    1              133
16    1                2
17    1               36
18    1                3
19    1                1
20    1               16
21    2               55
22    1                1
23    2                7
24    2                9
25    1                3
26    1               32
27    1                1
28    1                5
29    1               74
30    2                5
...   ...            ...
10819 1               15
10820 2               12
10821 1               64
10822 2                3
10823 1               10
10824 1               30
10825 1                4
10826 1               28
10827 1                7
10828 3               23
10829 1               65
10830 1               15
10831 1                1
10832 1              127
10833 1               43
10834 1               71
10835 1               35
10836 1               11
10837 1                1
10838 1                6
10839 1                9
10840 1                1
10841 2               28
10842 1              102
10843 1                7
10844 1               15
10845 1                3
10846 1               64
10847 1               64
10848 1               28

For answering all the questions I have selected only that particular which is required from, data frame

In [6]:
library(sqldf)
data <- arrange(Frame,desc(overall_rating))
data1 <- head(data,10)
ques1 <- print("Which are the top 10 players by overall rating?")
ans1 <- sqldf("SELECT player_name,overall_rating FROM data1")
ans1

[1] "Which are the top 10 players by overall rating?"

   player_name       overall_rating
1  Lionel Messi      94
2  Cristiano Ronaldo 93
3  Gianluigi Buffon  93
4  Wayne Rooney      93
5  Gregory Coupet    92
6  Xavi Hernandez    92
7  Alessandro Nesta  91
8  Andres Iniesta    91
9  Fabio Cannavaro   91
10 Iker Casillas     91

In [8]:
data2 <- arrange(Frame,desc(number_of_appear))
data3 <- head(data2,10)
ques2 <- print("Which are the top 10 players by number of appearances (with any team they played with)?")
ans2 <- sqldf("SELECT player_name,number_of_appear FROM data3")
ans2

[1] "Which are the top 10 players by number of appearances (with any team they played with)?"

   player_name          number_of_appear
1  Steve Mandanda       300
2  Stephane Ruffier     294
3  Gorka Iraizoz Moreno 286
4  Samir Handanovic     286
5  Tim Howard           282
6  Joe Hart             275
7  Cedric Carrasso      268
8  Daniel Congre        262
9  Gareth Barry         258
10 Marek Hamsik         257

In [9]:
data4 <- arrange(Frame,desc(gk_rating))
data5 <- head(data4,10)
ques3 <- print("Which are the top 10 goalkeepers by sum of gk attributes?")
ans3<- sqldf("SELECT player_name,gk_rating FROM data5")
ans3

[1] "Which are the top 10 goalkeepers by sum of gk attributes?"

   player_name       gk_rating
1  Gianluigi Buffon  449
2  Gregory Coupet    447
3  Petr Cech         445
4  Iker Casillas     442
5  Manuel Neuer      440
6  Sebastian Frey    437
7  Edwin van der Sar 436
8  David De Gea      429
9  Pepe Reina        428
10 Paul Robinson     426

In [10]:
data6 <- arrange(Frame,desc(num_of_leagues))
data7 <- head(data6,10)
ques4 <- print("Which are the top 10 players by number of leagues they played in?")
ans4<- sqldf("SELECT player_name,num_of_leagues FROM data7")
ans4

[1] "Which are the top 10 players by number of leagues they played in?"

   player_name           num_of_leagues
1  Gelson Fernandes      6
2  Filip Djuricic        5
3  Ricky van Wolfswinkel 5
4  Aleksandar Tonev      4
5  Alfred Finnbogason    4
6  Almen Abdi            4
7  Aly Cissokho          4
8  Angel Di Maria        4
9  Bojan Krkic           4
10 Bryan Ruiz            4

In [11]:
TeamFrame <- read.csv(file="team.csv",header=TRUE,sep=",")
TeamFrame

    X   team_api_id sum_goal team_long_name               build_up_play
1    1  1601        280      Ruch Chorzów                 133
2    2  1773        126      Oud-Heverlee Leuven          153
3    3  1957        287      Jagiellonia Bialystok        158
4    4  2033        138      S.C. Olhanense               147
5    5  2182        372      Lech Poznan                  147
6    6  2183        184      P. Warszawa                   NA
7    7  2186        235      Cracovia                     125
8    8  4049         35      Tubize                        NA
9    9  4064         27      Feirense                      NA
10  10  4087        180      Évian Thonon Gaillard FC     149
11  11  4170         31      US Boulogne Cote D'Opale      NA
12  12  6269         34      Novara                       179
13  13  6351         28      KAS Eupen                     NA
14  14  6367         27      Uniao da Madeira              NA
15  15  6391         37      GFC Ajaccio                  153
16  16  6403        292      FC Paços de Ferreira         142
17  17  6413        204      PEC Zwolle                   136
18  18  6421         55      Leixões SC                    NA
19  19  6433         74      Go Ahead Eagles              160
20  20  6493        128      AC Bellinzona                 NA
21  21  6547         29      FC Penafiel                  147
22  22  6601         38      FC Volendam                   NA
23  23  6631         24      FC Dordrecht                 134
24  24  7730         99      FC Lausanne-Sports           141
25  25  7788        119      SC Cambuur                   136
26  26  7794        165      SC Bastia                    174
27  27  7819        220      SM Caen                      157
28  28  7841        248      Rio Ave FC                   157
29  29  7842        167      Estoril Praia                167
30  30  7844        300      Vitória Guimarães            131
... ... ...         ...      ...                          ...
270 270  10214      332      CD Nacional                  167
271 271  10215      240      Académica de Coimbra         150
272 272  10217      366      ADO Den Haag                 162
273 273  10218      154      Excelsior                    163
274 274  10219      153      RKC Waalwijk                 142
275 275  10228      470      SC Heerenveen                150
276 276  10229      492      AZ                           154
277 277  10233      392      Genoa                        184
278 278  10235      489      Feyenoord                    131
279 279  10238      238      Vitória Setúbal              149
280 280  10242       71      ES Troyes AC                 148
281 281  10243      468      FC Zürich                    157
282 282  10249      344      Montpellier Hérault SC       162
283 283  10251      259      Hibernian                    148
284 284  10252      335      Aston Villa                  154
285 285  10260      582      Manchester United            124
286 286  10261      324      Newcastle United             152
287 287  10264      398      SC Braga                     145
288 288  10265      332      Wisla Kraków                 119
289 289  10267      484      Valencia CF                  116
290 290  10268       65      Elche CF                     151
291 291  10269      415      VfB Stuttgart                155
292 292  10278       36      Hércules Club de Fútbol      154
293 293  10281      170      Real Valladolid              148
294 294 108893       21      AC Arles-Avignon             156
295 295 158085      101      FC Arouca                    170
296 296 177361       33      Termalica Bruk-Bet Nieciecza  NA
297 297 188163       34      Tondela                       NA
298 298 208931       37      Carpi                        190
299 299 274581       71      Royal Excel Mouscron         150
    chance_creation defense_work
1   176             136
2   157             137
3   152             162
4   134             105
5   196             153
6   131             139
7   165             157
8    NA              NA
9    NA              NA
10  164             140
11  154             155
12  168             138
13  160             155
14   NA              NA
15  163             141
16  169             139
17  165             181
18  165              90
19  131             141
20  148             138
21  146             121
22   NA              NA
23  176             164
24  164             145
25  134             138
26  156             147
27  155             136
28  177             153
29  139             150
30  173             141
... ...             ...
270 150             141
271 166             138
272 145             142
273 136             106
274 133              99
275 152             138
276 173             166
277 134             127
278 146             129
279 158             132
280 147             137
281 151             146
282 142             157
283 139             124
284 146             133
285 133             163
286 147             131
287 166             120
288 101             157
289 146             147
290 164             158
291 172             117
292 178             160
293 147             134
294 138             158
295 160             113
296  NA              NA
297  NA              NA
298 160             115
299 150             140

In [12]:
teamdata1 <- arrange(TeamFrame,desc(build_up_play))
teamdata2 <- head(teamdata1,10)
teamques1 <- print("Which are the top 10 teams by sum of build up play attributes?")
teamans1 <- sqldf("SELECT team_long_name,build_up_play FROM teamdata2")
teamans1

[1] "Which are the top 10 teams by sum of build up play attributes?"

   team_long_name             build_up_play
1  Widzew Lódz                190
2  Widzew Lódz                190
3  Carpi                      190
4  Podbeskidzie Bielsko-Biala 189
5  FC Nantes                  189
6  Lazio                      188
7  Chievo Verona              187
8  Udinese                    185
9  Blackburn Rovers           185
10 Genoa                      184

In [13]:
taemques2 <- print("Which are the top 10 teams by sum of chance creation attributes?")
teamdata3 <- arrange(TeamFrame,desc(chance_creation))
teamdata4 <- head(teamdata3,10)
teamans2 <- sqldf("SELECT team_long_name,chance_creation FROM teamdata4")
teamans2

[1] "Which are the top 10 teams by sum of chance creation attributes?"

   team_long_name         chance_creation
1  Lazio                  220
2  Birmingham City        203
3  Falkirk                200
4  Hamilton Academical FC 197
5  Lech Poznan            196
6  Cagliari               196
7  Juventus               195
8  Bayer 04 Leverkusen    192
9  SV Werder Bremen       192
10 Roma                   191

In [14]:
teamques3 <- print("Which are the top 10 teams by sum of defense attributes?")
teamdata5 <- arrange(TeamFrame,desc(defense_work))
teamdata6 <- head(teamdata5,10)
teamans3 <- sqldf("SELECT team_long_name,defense_work FROM teamdata6")
teamans3

[1] "Which are the top 10 teams by sum of defense attributes?"

   team_long_name      defense_work
1  Odra Wodzislaw      205
2  KSV Roeselare       205
3  Falkirk             200
4  FC Barcelona        191
5  Lazio               190
6  Cagliari            187
7  FC Bayern Munich    184
8  Bayer 04 Leverkusen 183
9  Burnley             183
10 SV Werder Bremen    183

In [15]:
teamques4 <- print("Which are the top 10 teams by number of scored goals?")
teamdata6 <- arrange(TeamFrame,desc(sum_goal))
teamdata7 <- head(teamdata6,10)
teamans4 <- sqldf("SELECT team_long_name,sum_goal FROM teamdata7")
teamans4

[1] "Which are the top 10 teams by number of scored goals?"

   team_long_name    sum_goal
1  FC Barcelona      849
2  Real Madrid CF    843
3  Celtic            695
4  FC Bayern Munich  653
5  PSV               652
6  Ajax              647
7  FC Basel          619
8  Manchester City   606
9  Chelsea           583
10 Manchester United 582